# Setup
title:        xinszhou
tagline:      Take your time
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       xinszhou
  url:        http://yourhomepage.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
